backend:
  name: github
  repo: kupri-val/kids-site
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "announcements"
    label: "Объявления"
    folder: "content/announcements"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Текст", name: "body", widget: "markdown" }




